name: Build and merge containers

on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

permissions:
  packages: write
  contents: write
  id-token: write
  attestations: write

jobs:
  build_container:
    name: Build and Push Containers
    strategy:
      fail-fast: false
      matrix:
        model: <models>
        os: [blacksmith-2vcpu-ubuntu-2404, blacksmith-2vcpu-ubuntu-2404-arm]
    uses: taranis-ai/github-actions/.github/workflows/build-multiarch-bot-container.yml@master
    with:
      ghcr_image: ghcr.io/taranis-ai/{{ cookiecutter.__image_name }}
      model: {% raw %}${{ matrix.model }}{% endraw %}
      os: {% raw %}${{ matrix.os }}{% endraw %}

  merge_container:
    name: Merge Container Manifests
    needs: build_container
    strategy:
      fail-fast: false
      matrix:
        model: <models>
    uses: taranis-ai/github-actions/.github/workflows/merge-multiarch-bot-container.yml@master
    with:
      ghcr_image: ghcr.io/taranis-ai/{{ cookiecutter.__image_name }}
      model: {% raw %}${{ matrix.model }}{% endraw %}
      latest: {% raw %}${{ matrix.model == '<default_model>' }}{% endraw %}
