name: Test
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  test:
    name: Run Python Tests
    uses: taranis-ai/github-actions/.github/workflows/python-uv.yml@master