name: Smoke test
permissions:
  contents: read
on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

jobs:
  test_docker_deployment:
    if: {% raw %}${{ github.event.review.state == 'approved' || github.event_name == 'workflow_dispatch' }}{% endraw %}
    uses: taranis-ai/github-actions/.github/workflows/smoke-test.yml@master
    with:
      repo_name: {% raw %}${{ github.event.repository.name }}{% endraw %}
